apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql-container
          image: postgres:16.4
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgresql-pv
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: root
            - name: POSTGRES_DB
              value: postgres
      volumes:
        - name: postgresql-pv
          persistentVolumeClaim:
            claimName: postgres-claim
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  type: ClusterIP  # You can change this to NodePort or LoadBalancer if needed
  ports:
    - port: 5432    # Port on the service
      targetPort: 5432  # Port on the container      
  selector:
    app: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30008  # This port will be exposed on each Node
  selector:
    app: postgresql
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.0.10
  ports:
    - port: 5432       # Port exposed by the LoadBalancer
      targetPort: 5432 # Port on the container
  selector:
    app: postgresql      # Labels to select the pods

