apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app
        image: bookland-front:v3.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: angular-app-service
spec:
  selector:
    app: angular-app      # Labels to select the pods
  type: LoadBalancer
  externalIPs:
  - 192.168.0.51
  ports:
    - port: 80       # Port exposed by the LoadBalancer
      targetPort: 80 # Port on the container